[config]

[config.wallpaper]
set = true
command = "awww img --transition-type center {{ image }}"

[templates.btop]
input_path = './matugen-templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.firefox-website-colors]
 input_path = "./matugen-templates/firefox-colors.css"
 output_path = "~/.config/mozilla/firefox/default/chrome/colors.css"

[templates.vesktop]
input_path = './matugen-templates/system24.css'
output_path = '~/.config/vesktop/themes/system24.css'

[templates.gtk3]
input_path = './matugen-templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './matugen-templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'

[templates.hyprland]
input_path = './matugen-templates/hyprland-colors.lua'
output_path = '~/dotfiles/config/hypr/colors.lua'

[templates.kitty]
input_path = './matugen-templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kill -SIGUSR1 $(pgrep kitty)"

[templates.neovim]
input_path = "./matugen-templates/nvim-colors.json"
output_path = "~/.config/matugen/themes/nvim-colors.json"
post_hook = "pkill -SIGUSR1 nvim"

[templates.obs]
input_path = './matugen-templates/matugen.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'

[templates.obsidian]
input_path = './matugen-templates/obsidian.css'
output_path = '~/MyNotes/.obsidian/snippets/matugen.css'

[templates.opencode]
input_path = './matugen-templates/opencode-colors.json'
output_path = '~/dotfiles/config/opencode/themes/matugen.json'

[templates.quickshell]
input_path = './matugen-templates/quickshell.json'
output_path = '~/dotfiles/config/quickshell-dotfiles/themes/colors.json'
 
[templates.spotify]
input_path = './matugen-templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
post_hook = 'pgrep -x spicetify > /dev/null || spicetify apply -n'

[templates.starship]
input_path = './matugen-templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.tmux]
input_path = './matugen-templates/tmux-colors.conf'
output_path = '~/.config/tmux/generated.conf'
post_hook = 'tmux source-file ~/.config/tmux/generated.conf'

[templates.steam]
input_path = './matugen-templates/steam.css'
output_path = '~/.config/AdwSteamGtk/custom.css'
post_hook =  'adwaita-steam-gtk -i'
